#!/bin/bash

NPP=4          #use -1 for no mpi

CRE_SCF=1
CRE_BAND_NSCF=0
CRE_BAND=0
CRE_DOS_NSCF=0
CRE_DOS=0
CRE_PROJWFC=0
CRE_PP_SCF=1
CRE_PP=1

PREFIX="CeSiI"
D_PREF="CeSiI"

D_INN="/home/nano3/Desktop/SAKIB/LST/$D_PREF"
D_PSEUDO="/home/nano3/Desktop/SAKIB/Pseudo/"
D_QEE="/home/nano3/Desktop/SAKIB/qe-6.5/bin"

# D_INN="/media/sakib05/D/MaTerials/WS/My_Rig_4/$D_PREF"
# D_PSEUDO="/media/sakib05/D/MaTerials/UbuntuFiles/Pseudo/ONCVPSP"
# D_QEE="/media/sakib05/D/MaTerials/Deb/qe-6.5/bin"

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
    mkdir $PWD/$D_PREF/OUT
fi

A=8.30320726
C=30
NAT=24
NTYP=3
ECUTW=45
ECUTRHO=250


ATOM_SPE="\
Ce     140.116     Ce.pbe-spdfn-kjpaw_psl.1.0.0.UPF
Si     28.0855     Si.pbe-n-kjpaw_psl.1.0.0.UPF
I      126.904     I.pbe-dn-kjpaw_psl.1.0.0.UPF
"
ATOM_POS="\
Ce    0.0000000000    0.0000000000    1.9311042200
Si    2.0758018200    1.1984647400    0.0444332600
I     0.0000000000    2.3969294800    4.1028451600
Ce    0.0000000000    0.0000000000   -1.9311042200
Si    0.0000000000    2.3969294800   -0.0444332600
I     2.0758018200    1.1984647400   -4.1028451600
Ce   -2.0758018150    3.5953942100    1.9311042200
Si    0.0000000050    4.7938589500    0.0444332600
I    -2.0758018150    5.9923236900    4.1028451600
Ce   -2.0758018150    3.5953942100   -1.9311042200
Si   -2.0758018150    5.9923236900   -0.0444332600
I     0.0000000050    4.7938589500   -4.1028451600
Ce    4.1516036300    0.0000000000    1.9311042200
Si    6.2274054500    1.1984647400    0.0444332600
I     4.1516036300    2.3969294800    4.1028451600
Ce    4.1516036300    0.0000000000   -1.9311042200
Si    4.1516036300    2.3969294800   -0.0444332600
I     6.2274054500    1.1984647400   -4.1028451600
Ce    2.0758018150    3.5953942100    1.9311042200
Si    4.1516036350    4.7938589500    0.0444332600
I     2.0758018150    5.9923236900    4.1028451600
Ce    2.0758018150    3.5953942100   -1.9311042200
Si    2.0758018150    5.9923236900   -0.0444332600
I     4.1516036350    4.7938589500   -4.1028451600
"
K_SCF="9  9  1  0 0 0"
K_BANDS="\
4
gG 10
K  10
M  10
gG 10
"
K_DOS="24  24  1  0 0 0"
NGAUSS=-1           #PDOS

#PP_scf
ATOMIC_POSITIONS_pp="\
"

PREFIX_1=
NAT_1=24
NTYP_1=3
ATOM_SPE="\
"
ATOMIC_POSITIONS_1="\
"

PREFIX_2=
NAT_2=24
NTYP_2=3
ATOM_SPE="\
"
ATOMIC_POSITIONS_2="\
"

##################################--STARTING--#########################################
#Script file creation
touch $PWD/$D_PREF/$PREFIX.script
cat > $PWD/$D_PREF/$PREFIX.script << EOF
#!/bin/sh
F_PREFIX=$PREFIX
F_PREFIX_1=$PREFIX_1
F_PREFIX_2=$PREFIX_2
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Simulation";
EOF

#SCF file creation
if [ $CRE_SCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX.scf.in
cat > $PWD/$D_PREF/$PREFIX.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr	= 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_SCF

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.scf.in > \$D_OUT/\$F_PREFIX.scf.out;
echo "SCF Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.scf.in > \$D_OUT/\$F_PREFIX.scf.out;
echo "SCF Completed";
EOF
fi
fi

########################################################################################
#Band_nscf file creation
if [ $CRE_BAND_NSCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX.band_nscf.in
cat > $PWD/$D_PREF/$PREFIX.band_nscf.in <<EOF
&CONTROL
    calculation   = "bands"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr	= 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS crystal_b
$K_BANDS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
fi
fi

########################################################################################
#Band file creation
if [ $CRE_BAND == 1 ];then
touch $PWD/$D_PREF/$PREFIX.band.in
cat > $PWD/$D_PREF/$PREFIX.band.in <<EOF
&BANDS
    outdir	= "$D_INN/work/",
    prefix	= "$PREFIX",
    filband	= "$D_INN/OUT/$PREFIX.band",
    lsym	= .true.
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
fi
fi

########################################################################################
#DOS_nscf file creation
if [ $CRE_DOS_NSCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX.dos_nscf.in
cat > $PWD/$D_PREF/$PREFIX.dos_nscf.in <<EOF
&CONTROL
    calculation   = "nscf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'tetrahedra'
    vdw_corr	= 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_DOS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.dos_nscf.in > \$D_OUT/\$F_PREFIX.dos_nscf.out;
echo "DOS_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.dos_nscf.in > \$D_OUT/\$F_PREFIX.dos_nscf.out;
echo "DOS_NSCF Completed";
EOF
fi
fi

########################################################################################
#DOS file creation
if [ $CRE_DOS == 1 ];then
touch $PWD/$D_PREF/$PREFIX.dos.in
cat > $PWD/$D_PREF/$PREFIX.dos.in <<EOF
&DOS
    outdir = "$D_INN/work/"
    prefix = "$PREFIX"
    fildos = "$D_INN/OUT/$PREFIX.dos"
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/dos.x -i \$D_IN/\$F_PREFIX.dos.in > \$D_OUT/\$F_PREFIX.dos.out;
echo "DOS Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/dos.x -i \$D_IN/\$F_PREFIX.dos.in > \$D_OUT/\$F_PREFIX.dos.out;
echo "DOS Completed";
EOF
fi
fi

########################################################################################
#PROJWFC file creation
if [ $CRE_PROJWFC == 1 ];then
touch $PWD/$D_PREF/$PREFIX.projwfc.in
cat > $PWD/$D_PREF/$PREFIX.projwfc.in <<EOF
&PROJWFC
    outdir = "$D_INN/work/"
    prefix = "$PREFIX"
    ngauss = $NGAUSS
    filpdos = "$D_INN/OUT/$PREFIX"
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/projwfc.x -i \$D_IN/\$F_PREFIX.projwfc.in > \$D_OUT/\$F_PREFIX.projwfc.out;
echo "PDOS Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/projwfc.x -i \$D_IN/\$F_PREFIX.projwfc.in > \$D_OUT/\$F_PREFIX.projwfc.out;
echo "PDOS Completed";
EOF
fi
fi

########################################################################################
#PP_scf file creation

if [ $CRE_PP_SCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX.pp_scf.in
cat > $PWD/$D_PREF/$PREFIX.pp_scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS_pp
K_POINTS {automatic}
$K_SCF

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.pp_scf.in > \$D_OUT/\$F_PREFIX.pp_scf.out;
echo "PP SCF PREFIX Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.pp_scf.in > \$D_OUT/\$F_PREFIX.pp_scf.out;
echo "PP SCF PREFIX Completed";
EOF
fi
fi

########################################################################################
#PP_scf_1 file creation

if [ $CRE_PP_SCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX_1.pp_scf.in
cat > $PWD/$D_PREF/$PREFIX_1.pp_scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX_1"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT_1
    ntyp        =  $NTYP_1
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE_1
ATOMIC_POSITIONS (angstrom)
$ATOM_POS_1
K_POINTS {automatic}
$K_SCF

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX_1.pp_scf.in > \$D_OUT/\$F_PREFIX_1.pp_scf.out;
echo "PP SCF PREFIX_1 Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX_1.pp_scf.in > \$D_OUT/\$F_PREFIX_1.pp_scf.out;
echo "PP SCF PREFIX_1 Completed";
EOF
fi
fi

########################################################################################
#PP_scf_2 file creation

if [ $CRE_PP_SCF == 1 ];then
touch $PWD/$D_PREF/$PREFIX_2.pp_scf.in
cat > $PWD/$D_PREF/$PREFIX_2.pp_scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX_2"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT_2
    ntyp        =  $NTYP_2
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE_2
ATOMIC_POSITIONS (angstrom)
$ATOM_POS_2
K_POINTS {automatic}
$K_SCF

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX_2.pp_scf.in > \$D_OUT/\$F_PREFIX_2.pp_scf.out;
echo "PP SCF PREFIX_2 Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX_2.pp_scf.in > \$D_OUT/\$F_PREFIX_2.pp_scf.out;
echo "PP SCF PREFIX_2 Completed";
EOF
fi
fi

########################################################################################
#PP file creation

if [ $CRE_PP == 1 ];then
touch $PWD/$D_PREF/$PREFIX.pp.in
cat > $PWD/$D_PREF/$PREFIX.pp.in <<EOF
&INPUTPP
    prefix      = "$PREFIX"
    outdir      = "$D_INN/work/"
    plot_num    = 0
    filplot     = "$D_INN/OUT/$PREFIX.charge"
/
&PLOT
    iflag       = 3
    output_format = 6
    fileout     = "$D_INN/OUT/$PREFIX.cube"
/

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pp.x -i \$D_IN/\$F_PREFIX.pp.in > \$D_OUT/\$F_PREFIX.pp.out;
echo "$PREFIX PP Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pp.x -i \$D_IN/\$F_PREFIX.pp.in > \$D_OUT/\$F_PREFIX.pp.out;
echo "$PREFIX PP Completed";
EOF
fi
fi


########################################################################################
#PP file creation 1

if [ $CRE_PP == 1 ];then
touch $PWD/$D_PREF/$PREFIX.pp.in
cat > $PWD/$D_PREF/$PREFIX.pp.in <<EOF
&INPUTPP
    prefix      = "$PREFIX_1"
    outdir      = "$D_INN/work/"
    plot_num    = 0
    filplot     = "$D_INN/OUT/$PREFIX_1.charge"
/
&PLOT
    iflag       = 3
    output_format = 6
    fileout     = "$D_INN/OUT/$PREFIX_1.cube"
/

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pp.x -i \$D_IN/\$F_PREFIX_1.pp.in > \$D_OUT/\$F_PREFIX_1.pp.out;
echo "$PREFIX_1 PP Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pp.x -i \$D_IN/\$F_PREFIX_1.pp.in > \$D_OUT/\$F_PREFIX_1.pp.out;
echo "$PREFIX_1 PP Completed";
EOF
fi
fi


########################################################################################
#PP file creation 2

if [ $CRE_PP == 1 ];then
touch $PWD/$D_PREF/$PREFIX.pp.in
cat > $PWD/$D_PREF/$PREFIX.pp.in <<EOF
&INPUTPP
    prefix      = "$PREFIX_2"
    outdir      = "$D_INN/work/"
    plot_num    = 0
    filplot     = "$D_INN/OUT/$PREFIX_2.charge"
/
&PLOT
    iflag       = 3
    output_format = 6
    fileout     = "$D_INN/OUT/$PREFIX_2.cube"
/

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pp.x -i \$D_IN/\$F_PREFIX_2.pp.in > \$D_OUT/\$F_PREFIX_2.pp.out;
echo "$PREFIX_2 PP Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pp.x -i \$D_IN/\$F_PREFIX_2.pp.in > \$D_OUT/\$F_PREFIX_2.pp.out;
echo "$PREFIX_2 PP Completed";
EOF
fi
fi

########################################################################################
#ChargeDiff file creation

if [ $CRE_PP == 1 ];then
touch $PWD/$D_PREF/$PREFIX.chdiff.in
cat > $PWD/$D_PREF/$PREFIX.chdiff.in <<EOF
&INPUTPP
/
&PLOT
    nfile       = 3
    filepp(1)   = "$D_INN/OUT/$PREFIX.charge", 
    filepp(2)   = "$D_INN/OUT/$PREFIX_1.charge", 
    filepp(3)   = "$D_INN/OUT/$PREFIX_2.charge", 
    weight(1)   = 1
    weight(2)   =-1
    weight(3)   =-1
    iflag       = 3
    output_format= 6
    fileout     = "$D_INN/OUT/${PREFIX}_chargediff.cube"
/

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
\$D_QE/pp.x -i \$D_IN/\$F_PREFIX.chdiff.in > \$D_OUT/\$F_PREFIX.chdiff.out;
echo "ChargeDiff Completed";
EOF
else
cat >> $PWD/$D_PREF/$PREFIX.script << EOF
mpirun -np \$NP \$D_QE/pp.x -i \$D_IN/\$F_PREFIX.chdiff.in > \$D_OUT/\$F_PREFIX.chdiff.out;
echo "ChargeDiff Completed";
EOF
fi
fi

###################################--THE_END--##########################################

