#!/bin/bash

NPP=4

PREFIX="BN+CeSiI"
D_PREF="BN+CeSiI"
Z_START_VAL=6.6028451600
Z_STOP_VAL=8.5785937200
INCREM=0.1
BUCKLING=0

A=8.30320726
C=30
NAT=24
NTYP=3
ECUTW=45
ECUTRHO=250

ATOM_SPE="\
Ce     140.116     Ce.pbe-spdfn-kjpaw_psl.1.0.0.UPF
Si     28.0855     Si.pbe-n-kjpaw_psl.1.0.0.UPF
I      126.904     I.pbe-dn-kjpaw_psl.1.0.0.UPF
"

K_SCF="9  9  1  0 0 0"
K_BANDS="\
4
gG 10
K  10
M  10
gG 10
"

Z_VAL_1=$Z_START_VAL
Z_VAL_2=$(calc $Z_START_VAL+$BUCKLING)

D_INN="/home/nano3/Desktop/SAKIB/LST/$D_PREF"
D_PSEUDO="/home/nano3/Desktop/SAKIB/Pseudo/"
D_QEE="/home/nano3/Desktop/SAKIB/qe-6.5/bin"

# D_INN="/mnt/h/SAKIB/store/$D_PREF"
# D_PSEUDO="/mnt/h/SAKIB/pseudo/"
# D_QEE="/media/sakib_05/G4M35/MaTerials/UbuntuFiles/qe-6.3/bin"

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
    mkdir $PWD/$D_PREF/OUT
fi

touch $PWD/$D_PREF/${PREFIX}.script
cat > $PWD/$D_PREF/${PREFIX}.script << EOF
#!/bin/sh
F_PREFIX=${PREFIX}
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Relax Calculation for ${PREFIX}"

EOF

#SCF file creation
for Z_VAL in $(seq $Z_START_VAL $INCREM $Z_STOP_VAL)
do
Z_VAL_1=$Z_VAL
Z_VAL_2=$(calc $Z_VAL+$BUCKLING | awk {'print $1'})

ATOM_POS="\
Ce    0.0000000000    0.0000000000    1.9311042200
Si    2.0758018200    1.1984647400    0.0444332600
I     0.0000000000    2.3969294800    4.1028451600
Ce    0.0000000000    0.0000000000   -1.9311042200
Si    0.0000000000    2.3969294800   -0.0444332600
I     2.0758018200    1.1984647400   -4.1028451600
Ce   -2.0758018150    3.5953942100    1.9311042200
Si    0.0000000050    4.7938589500    0.0444332600
I    -2.0758018150    5.9923236900    4.1028451600
Ce   -2.0758018150    3.5953942100   -1.9311042200
Si   -2.0758018150    5.9923236900   -0.0444332600
I     0.0000000050    4.7938589500   -4.1028451600
Ce    4.1516036300    0.0000000000    1.9311042200
Si    6.2274054500    1.1984647400    0.0444332600
I     4.1516036300    2.3969294800    4.1028451600
Ce    4.1516036300    0.0000000000   -1.9311042200
Si    4.1516036300    2.3969294800   -0.0444332600
I     6.2274054500    1.1984647400   -4.1028451600
Ce    2.0758018150    3.5953942100    1.9311042200
Si    4.1516036350    4.7938589500    0.0444332600
I     2.0758018150    5.9923236900    4.1028451600
Ce    2.0758018150    3.5953942100   -1.9311042200
Si    2.0758018150    5.9923236900   -0.0444332600
I     4.1516036350    4.7938589500   -4.1028451600
B     0.0000000000    0.0000000000    $Z_VAL_1
N     0.0000000000    1.5979529820    $Z_VAL_1
B    -1.3838678770    2.3969294730    $Z_VAL_1
N    -1.3838678770    3.9948824550    $Z_VAL_1
B    -2.7677357540    4.7938589460    $Z_VAL_1
N    -2.7677357540    6.3918119280    $Z_VAL_1
B     2.7677357530    0.0000000000    $Z_VAL_1
N     2.7677357530    1.5979529820    $Z_VAL_1
B     1.3838678760    2.3969294730    $Z_VAL_1
N     1.3838678760    3.9948824550    $Z_VAL_1
B    -0.0000000010    4.7938589460    $Z_VAL_1
N    -0.0000000010    6.3918119280    $Z_VAL_1
B     5.5354715060    0.0000000000    $Z_VAL_1
N     5.5354715060    1.5979529820    $Z_VAL_1
B     4.1516036290    2.3969294730    $Z_VAL_1
N     4.1516036290    3.9948824550    $Z_VAL_1
B     2.7677357520    4.7938589460    $Z_VAL_1
N     2.7677357520    6.3918119280    $Z_VAL_1
"
# YOU CAN COPY FROM HERE
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2

##################################--STARTING--#########################################
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_SCF

EOF

Z_VAL_OLD=$(calc $Z_VAL-$INCREM)

if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
fi

########################################################################################
#Band_nscf file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.band_nscf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.band_nscf.in <<EOF
&CONTROL
    calculation   = "bands"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS crystal_b
$K_BANDS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
fi

########################################################################################
#Band file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.band.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.band.in <<EOF
&BANDS
    outdir  = "$D_INN/work/",
    prefix  = "${PREFIX}_$Z_VAL",
    filband = "$D_INN/OUT/${PREFIX}_$Z_VAL.band",
    lsym    = .true.
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
\$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
mpirun -np \$NP \$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
fi
# NEW_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL.scf.out)
# OLD_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL_OLD.scf.out)
# if [[ \$NEW_VAL < \$OLD_VAL ]]; then
#     exit
# fi

# EOF
done

