#!/bin/bash

NPP=4

#=======================GEN=========================================================
CRE_GEN=
ATOM_POS_GEN="\
I      2.03778243      1.17651424     -1.64331411
Zn    -0.00000000      0.00000000     -0.00000000
I      0.00000000      2.35302847      1.64331411
Si     0.0000000000    0.0000000000    5.44331411
Si     0.0000000000    2.3136887917    5.7785531516
"
#################################################
CRE_SCF=1
CRE_BAND_NSCF=1
CRE_BAND=1
K_SCF="12  12  1  0 0 0"
K_BANDS="\
4
gG 20
M  20
K  20
gG 20
"
#======================RELX=========================================================
PREFIX="Si+ZnBr2_I_rlx_2"
D_PREF=$PREFIX

A=3.76141954
C=25
NAT=5
NTYP=3
ECUTW=45
ECUTRHO=250

ATOM_SPE="\
Zn     65.38       Zn_ONCV_PBE_sr.upf
Br     79.904      Br_ONCV_PBE_sr.upf
Si     28.0855     Si_ONCV_PBE_sr.upf
"
DIST=1.51007595
#################################################
INCREM=0.01
BUCKLING=0.5551267706
#======================NOW_JUST_THE_ATOMIC_POSITIONS================================
PREFIX_GEN=${PREFIX}_
D_PREF_GEN=${PREFIX}_
Z_START_VAL=$(calc $DIST+3.0)
Z_STOP_VAL=$(calc $DIST+4.0)

Z_START_VAL=5.21007595
Z_STOP_VAL=5.31007595

Z_VAL_1=$Z_START_VAL
Z_VAL_2=$(calc $Z_START_VAL+$BUCKLING)
# MID_ATOM=$(printf %.10f $(calc 4.0074265411/1.732050808 | tr "~" " ")) #TEMPORARY

D_INN="/home/nano3/Desktop/SAKIB/LST2/$D_PREF"
D_INN_GEN=${D_INN}_
D_PSEUDO="/home/nano3/Desktop/SAKIB/Pseudo/"
D_QEE="/home/nano3/Desktop/SAKIB/qe-6.5/bin"

#======================END_OF_INPUT/BUT_ATOMIC_POSITIONS!===========================

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
    mkdir $PWD/$D_PREF/OUT
fi


touch $PWD/$D_PREF/${PREFIX}.script
cat > $PWD/$D_PREF/${PREFIX}.script << EOF
#!/bin/sh
F_PREFIX=${PREFIX}
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Relax Calculation for ${PREFIX}"

EOF

#SCF file creation
for Z_VAL in $(seq $Z_START_VAL $INCREM $Z_STOP_VAL)
do
Z_VAL_1=$Z_VAL
Z_VAL_2=$(calc $Z_VAL+$BUCKLING | awk {'print $1'})

ATOM_POS="\
Zn     0.0000000000    2.1716565900    0.00000000
Br     0.0000000000    0.0000000000    1.51007595
Br     1.8807097700    1.0858282900   -1.51007595
Si     0.0000000000    0.0000000000    $Z_VAL_1
Si     0.0000000000    2.1716565840    $Z_VAL_2
"
# YOU CAN COPY FROM HERE
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2

##################################--STARTING--#########################################
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_SCF

EOF

Z_VAL_OLD=$(calc $Z_VAL-$INCREM)

if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
fi

# NEW_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL.scf.out)
# OLD_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL_OLD.scf.out)
# if [[ \$NEW_VAL < \$OLD_VAL ]]; then
#     exit
# fi

# EOF
done


if [[ $CRE_GEN -eq 1 ]]; then

if [ ! -d "$PWD/$D_PREF_GEN" ]; then
    mkdir $PWD/$D_PREF_GEN
    mkdir $PWD/$D_PREF_GEN/OUT
fi

##################################--STARTING--#########################################
#Script file creation
touch $PWD/$D_PREF_GEN/$PREFIX_GEN.script
cat > $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
#!/bin/sh
F_PREFIX=$PREFIX_GEN
D_IN="$D_INN_GEN"
D_OUT="$D_INN_GEN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Simulation";
EOF

#SCF file creation
if [ $CRE_SCF == 1 ];then
touch $PWD/$D_PREF_GEN/$PREFIX_GEN.scf.in
cat > $PWD/$D_PREF_GEN/$PREFIX_GEN.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN_GEN/work/"
    prefix        = "$PREFIX_GEN"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS_GEN
K_POINTS {automatic}
$K_SCF

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.scf.in > \$D_OUT/\$F_PREFIX.scf.out;
echo "SCF Completed";
EOF
else
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.scf.in > \$D_OUT/\$F_PREFIX.scf.out;
echo "SCF Completed";
EOF
fi
fi

########################################################################################
#Band_nscf file creation
if [ $CRE_BAND_NSCF == 1 ];then
touch $PWD/$D_PREF_GEN/$PREFIX_GEN.band_nscf.in
cat > $PWD/$D_PREF_GEN/$PREFIX_GEN.band_nscf.in <<EOF
&CONTROL
    calculation   = "bands"
    outdir        = "$D_INN_GEN/work/"
    prefix        = "$PREFIX_GEN"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS_GEN
K_POINTS crystal_b
$K_BANDS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
fi
fi

########################################################################################
#Band file creation
if [ $CRE_BAND == 1 ];then
touch $PWD/$D_PREF_GEN/$PREFIX_GEN.band.in
cat > $PWD/$D_PREF_GEN/$PREFIX_GEN.band.in <<EOF
&BANDS
    outdir  = "$D_INN_GEN/work/",
    prefix  = "$PREFIX_GEN",
    filband = "$D_INN_GEN/OUT/$PREFIX_GEN.band",
    lsym    = .true.
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
\$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
else
cat >> $PWD/$D_PREF_GEN/$PREFIX_GEN.script << EOF
mpirun -np \$NP \$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
fi
fi

########################################################################################

fi


