#!/bin/bash

NPP=4

PREFIX="Si+ZnI2_II"
D_PREF="Si+ZnI2_II_interlayer_dist"
Z_START_VAL=4.9533141100
Z_STOP_VAL=6.9533141100
INCREM=0.2
BUCKLING=0.3352390416

A=4.07556486
C=25
NAT=5
NTYP=3
ECUTW=45
ECUTRHO=250

ATOM_SPE="\
Zn     65.38       Zn_ONCV_PBE_sr.upf
I     126.9044     I_ONCV_PBE_sr.upf
Si     28.0855     Si_ONCV_PBE_sr.upf
"

K_SCF="12  12  1  0 0 0"
K_BANDS="\
4
gG 20
M  20
K  20
gG 20
"

Z_VAL_1=$Z_START_VAL
Z_VAL_2=$(calc $Z_START_VAL+$BUCKLING)
D_INN="/home/nano3/Desktop/SAKIB/LST2/$D_PREF"
D_PSEUDO="/home/nano3/Desktop/SAKIB/Pseudo/"
D_QEE="/home/nano3/Desktop/SAKIB/qe-6.5/bin"

# D_INN="/mnt/h/SAKIB/store/$D_PREF"
# D_PSEUDO="/mnt/h/SAKIB/pseudo/"
# D_QEE="/media/sakib_05/G4M35/MaTerials/UbuntuFiles/qe-6.3/bin"

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
    mkdir $PWD/$D_PREF/OUT
fi

touch $PWD/$D_PREF/${PREFIX}.script
cat > $PWD/$D_PREF/${PREFIX}.script << EOF
#!/bin/sh
F_PREFIX=${PREFIX}
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Relax Calculation for ${PREFIX}"

EOF

#SCF file creation
for Z_VAL in $(seq $Z_START_VAL $INCREM $Z_STOP_VAL)
do
Z_VAL_1=$Z_VAL
Z_VAL_2=$(calc $Z_VAL+$BUCKLING | awk {'print $1'})
Z_VAL_PREFIX=$(printf %.4f $Z_VAL)

ATOM_POS="\
I      2.0377824300    1.1765142400   -1.6433141100
Zn     0.0000000000    0.0000000000    0.0000000000
I      0.0000000000    2.3530284700    1.6433141100
Si     0.0000000000    2.3530284690    $Z_VAL_1
Si     0.0000000000    0.0000000000    $Z_VAL_2
"
# YOU CAN COPY FROM HERE
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2

##################################--STARTING--#########################################
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.scf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL_PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_SCF

EOF

Z_VAL_OLD=$(calc $Z_VAL-$INCREM)

if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.scf.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.scf.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
fi

########################################################################################
#Band_nscf file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.band_nscf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.band_nscf.in <<EOF
&CONTROL
    calculation   = "bands"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL_PREFIX"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-8
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS crystal_b
$K_BANDS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.band_nscf.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.band_nscf.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
fi

########################################################################################
#Band file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.band.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL_PREFIX.band.in <<EOF
&BANDS
    outdir  = "$D_INN/work/",
    prefix  = "${PREFIX}_$Z_VAL_PREFIX",
    filband = "$D_INN/OUT/${PREFIX}_$Z_VAL_PREFIX.band",
    lsym    = .true.
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/bands.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.band.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.band.out;
echo "BAND Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/bands.x -i \$D_IN/${PREFIX}_$Z_VAL_PREFIX.band.in > \$D_OUT/${PREFIX}_$Z_VAL_PREFIX.band.out;
echo "BAND Completed";
EOF
fi
# NEW_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL_PREFIX.scf.out)
# OLD_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL_PREFIX_OLD.scf.out)
# if [[ \$NEW_VAL < \$OLD_VAL ]]; then
#     exit
# fi

# EOF
done

