#!/bin/bash

NPP=-1

PREFIX="Ge+SiC_III_"
D_PREF="Ge+SiC_III"
Z_START_VAL=2.8
Z_STOP_VAL=3.6
INCREM=0.2
BUCKLING=0.672

A=12.24
C=20
NAT=50
NTYP=3
ECUTW=30
ECUTRHO=120

ATOM_SPE="\
Ge 72.59  Ge.pbe-mt_fhi.UPF
C 12.0107 C.pbe-mt_fhi.UPF
Si 28.0855 Si.pbe-mt_fhi.UPF
"

K_SCF="3  3  1  0 0 0"
K_BANDS="\
4
0.0000000  0.5000000  0.0000000  20 !M
0.3333333  0.3333333  0.0000000  20 !k
0.0000000  0.0000000  0.0000000  20 !G
0.0000000  0.5000000  0.0000000  20 !M
"

Z_VAL_1=$Z_START_VAL
Z_VAL_2=$(calc $Z_START_VAL+$BUCKLING)

D_INN="/home/nano3/Desktop/RAYID/Ge+SiC/$D_PREF"
D_PSEUDO="/home/nano3/Desktop/RAYID/qe-6.3/bin/pseudo/"
D_QEE="/home/nano3/Desktop/RAYID/qe-6.3/bin"

# D_INN="/mnt/h/SAKIB/store/$D_PREF"
# D_PSEUDO="/mnt/h/SAKIB/pseudo/"
# D_QEE="/media/sakib_05/G4M35/MaTerials/UbuntuFiles/qe-6.3/bin"

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
    mkdir $PWD/$D_PREF/OUT
fi

touch $PWD/$D_PREF/${PREFIX}.script
cat > $PWD/$D_PREF/${PREFIX}.script << EOF
#!/bin/sh
F_PREFIX=${PREFIX}
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started Band vs ID Calculation for ${PREFIX}"

EOF

#SCF file creation
for Z_VAL in $(seq $Z_START_VAL $INCREM $Z_STOP_VAL)
do
Z_VAL_1=$Z_VAL
Z_VAL_2=$(calc $Z_VAL+$BUCKLING | awk {'print $1'})

ATOM_POS="\
Ge   0.000000000   2.261600000   $Z_VAL_2
Ge  -2.040000000   5.794983647   $Z_VAL_2
Ge  -4.080000000   9.328367294   $Z_VAL_2
Ge   4.080000000   2.261600000   $Z_VAL_2
Ge   2.040000000   3.439383647   $Z_VAL_1
Ge   2.040000000   5.794983647   $Z_VAL_2
Ge   0.000000000   6.972767294   $Z_VAL_1
Ge   0.000000000   9.328367294   $Z_VAL_2
Ge  -2.040000000  10.506150941   $Z_VAL_1
Ge   8.160000000   2.261600000   $Z_VAL_2
Ge   6.120000000   3.439383647   $Z_VAL_1
Ge   6.120000000   5.794983647   $Z_VAL_2
Ge   4.080000000   6.972767294   $Z_VAL_1
Ge   4.080000000   9.328367294   $Z_VAL_2
Ge   2.040000000  10.506150941   $Z_VAL_1
Ge   10.20000000   3.439383647   $Z_VAL_1
Ge   8.160000000   6.972767294   $Z_VAL_1
Ge   6.120000000  10.506150941   $Z_VAL_1
Si   0.000000000   1.700000000   0.000000000
Si  -1.530000000   4.350037736   0.000000000
Si  -3.060000000   7.000075472   0.000000000
Si  -4.590000000   9.650113208   0.000000000
Si   3.060000000   1.700000000   0.000000000
C    1.530000000   2.583337736   0.000000000
Si   1.530000000   4.350037736   0.000000000
C    0.000000000   5.233375472   0.000000000
Si   0.000000000   7.000075472   0.000000000
C   -1.530000000   7.883413208   0.000000000
Si  -1.530000000   9.650113208   0.000000000
C   -3.060000000  10.533450944   0.000000000
Si   6.120000000   1.700000000   0.000000000
C    4.590000000   2.583337736   0.000000000
Si   4.590000000   4.350037736   0.000000000
C    3.060000000   5.233375472   0.000000000
Si   3.060000000   7.000075472   0.000000000
C    1.530000000   7.883413208   0.000000000
Si   1.530000000   9.650113208   0.000000000
C    0.000000000  10.533450944   0.000000000
Si   9.180000000   1.700000000   0.000000000
C    7.650000000   2.583337736   0.000000000
Si   7.650000000   4.350037736   0.000000000
C    6.120000000   5.233375472   0.000000000
Si   6.120000000   7.000075472   0.000000000
C    4.590000000   7.883413208   0.000000000
Si   4.590000000   9.650113208   0.000000000
C    3.060000000  10.533450944   0.000000000
C   10.710000000   2.583337736   0.000000000
C    9.180000000   5.233375472   0.000000000
C    7.650000000   7.883413208   0.000000000
C    6.120000000  10.533450944   0.000000000
"
# YOU CAN COPY FROM HERE
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2
#   $Z_VAL_1
#   $Z_VAL_2

##################################--STARTING--#########################################
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'm-p'
    degauss     =  0.006
    vdw_corr    = 'grimme-d2'
/

&ELECTRONS
    conv_thr         =  1.00000e-4
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
$K_SCF

EOF

Z_VAL_OLD=$(calc $Z_VAL-$INCREM)

if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
\$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.band_nscf.in > \$D_OUT/${PREFIX}_$Z_VAL.band_nscf.out;
echo "Completed >> $Z_VAL Ang band_nscf";
\$D_QE/bands.x -i \$D_IN/${PREFIX}_$Z_VAL.band.in > \$D_OUT/${PREFIX}_$Z_VAL.band.out;
echo "Completed >> $Z_VAL Ang band";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/${PREFIX}_$Z_VAL.scf.in > \$D_OUT/${PREFIX}_$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF
fi

########################################################################################
#Band_nscf file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.band_nscf.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.band_nscf.in <<EOF
&CONTROL
    calculation   = "bands"
    outdir        = "$D_INN/work/"
    prefix        = "${PREFIX}_$Z_VAL"
    pseudo_dir    = "$D_PSEUDO"
    restart_mode  = "from_scratch"
    verbosity     = "high"
/

&SYSTEM
    ibrav       =  4
    a           =  $A
    c           =  $C
    nat         =  $NAT
    ntyp        =  $NTYP
    input_dft   = 'PBE'
    ecutwfc     =  $ECUTW
    ecutrho     =  $ECUTRHO
    occupations = 'smearing'
    smearing    = 'm-p'
    degauss     =  0.006
    vdw_corr    = 'grimme-d2'
/

&ELECTRONS
    conv_thr         =  1.00000e-4
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
$ATOM_SPE
ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS crystal_b
$K_BANDS

EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
\$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/\$F_PREFIX.band_nscf.in > \$D_OUT/\$F_PREFIX.band_nscf.out;
echo "BAND_NSCF Completed";
EOF
fi

########################################################################################
#Band file creation
touch $PWD/$D_PREF/${PREFIX}_$Z_VAL.band.in
cat > $PWD/$D_PREF/${PREFIX}_$Z_VAL.band.in <<EOF
&BANDS
    outdir  = "$D_INN/work/",
    prefix  = "${PREFIX}_$Z_VAL",
    filband = "$D_INN/OUT/${PREFIX}_$Z_VAL.band",
    lsym    = .true.
/
EOF
if [ $NPP == -1 ];then
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
\$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
else
cat >> $PWD/$D_PREF/${PREFIX}_$Z_VAL.script << EOF
mpirun -np \$NP \$D_QE/bands.x -i \$D_IN/\$F_PREFIX.band.in > \$D_OUT/\$F_PREFIX.band.out;
echo "BAND Completed";
EOF
fi
# NEW_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL.scf.out)
# OLD_VAL=\$(grep ! $D_INN/OUT/${PREFIX}_$Z_VAL_OLD.scf.out)
# if [[ \$NEW_VAL < \$OLD_VAL ]]; then
#     exit
# fi

# EOF
done

