#!/bin/bash

NPP=2

PREFIX="C_Unit_"
D_PREF="C_Unit_ECUTrho"
Z_START_VAL=100
Z_STOP_VAL=350
INCREM=10
Z_VAL=$Z_START_VAL
D_INN="/media/sakib_05/G4M35/MaTerials/WS/SCF_KP_T/$D_PREF"
D_QEE="/media/sakib_05/G4M35/MaTerials/UbuntuFiles/qe-6.3/bin"

if [ ! -d "$PWD/$D_PREF" ]; then
    mkdir $PWD/$D_PREF
fi

touch $PWD/$D_PREF/$PREFIX\_ECUTrho.script
cat > $PWD/$D_PREF/$PREFIX\_ECUTrho.script << EOF
#!/bin/sh
F_PREFIX=$PREFIX
D_IN="$D_INN"
D_OUT="$D_INN/OUT"
D_QE="$D_QEE"
NP="$NPP"

if [ ! -d "\$D_OUT" ]; then
    mkdir \$D_OUT
fi

echo "Started ECUTrho Test";
EOF

#SCF file creation
for Z_VAL in $(seq $Z_START_VAL $INCREM $Z_STOP_VAL)
do
ATOM_POS="\
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.4202816620    0.0000000000
"

##################################--STARTING--#########################################
touch $PWD/$D_PREF/ECUTrho_$PREFIX$Z_VAL.scf.in
cat > $PWD/$D_PREF/ECUTrho_$PREFIX$Z_VAL.scf.in <<EOF
&CONTROL
    calculation   = "scf"
    outdir        = "$D_INN/work/"
    prefix        = "$PREFIX$Z_VAL"
    pseudo_dir    = "/media/sakib_05/G4M35/MaTerials/UbuntuFiles/Pseudo/pseudoR/"
    restart_mode  = "from_scratch"
    verbosity     = 'high'
/

&SYSTEM
    ibrav       =  4
    a           =  2.46
    c           =  25
    nat         =  2
    ntyp        =  1
    input_dft   = 'PBE'
    ecutwfc     =  45
    ecutrho     =  $Z_VAL
    occupations = 'smearing'
    smearing    = 'mp'
    degauss     =  0.005
    vdw_corr    = 'DFT-D'
/

&ELECTRONS
    conv_thr         =  1.00000e-6
    mixing_beta      =  0.7
/

ATOMIC_SPECIES
C      12.011     C.pbe-mt_fhi.UPF

ATOMIC_POSITIONS (angstrom)
$ATOM_POS
K_POINTS {automatic}
6  6  1  0 0 0
!N      14.00674   N.pbe-mt_fhi.UPF
!In     114.81800  In.pbe-d-mt_fhi.UPF

EOF

cat >> $PWD/$D_PREF/$PREFIX\_ECUTrho.script << EOF
mpirun -np \$NP \$D_QE/pw.x -i \$D_IN/$PREFIX$Z_VAL.scf.in > \$D_OUT/$PREFIX$Z_VAL.scf.out;
echo "Completed >> $Z_VAL Ang";
EOF

done
